-- Add geographic and device columns to clicks table
alter table public.clicks
  add column if not exists country text,
  add column if not exists city text,
  add column if not exists device_type text, -- mobile/desktop/tablet/bot
  add column if not exists browser text,
  add column if not exists os text,
  add column if not exists device_brand text;
-- Create indexes for analytics queries
create index if not exists clicks_country_idx on public.clicks (country) where country is not null;
create index if not exists clicks_device_type_idx on public.clicks (device_type) where device_type is not null;
create index if not exists clicks_browser_idx on public.clicks (browser) where browser is not null;
create index if not exists clicks_user_agent_idx on public.clicks (user_agent);
-- Add notification settings table for webhook/telegram
create table if not exists public.user_notification_settings (
  id uuid default gen_random_uuid() primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  webhook_url text,
  telegram_bot_token text,
  telegram_chat_id text,
  notify_on_click boolean default true,
  notify_threshold integer default 0, -- 0 = all clicks, >0 = notify only after N clicks
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id)
);
-- Enable RLS
alter table public.user_notification_settings enable row level security;
-- RLS Policy
 drop policy if exists "Users can manage own notification settings"
  on public.user_notification_settings;
create policy "Users can manage own notification settings"
  on public.user_notification_settings
  for all
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());
-- Add notification log table
create table if not exists public.notification_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  link_id uuid references public.links(id) on delete cascade,
  notification_type text not null, -- webhook, telegram
  status text not null, -- success, failed
  message text,
  created_at timestamptz not null default now()
);
create index if not exists notification_logs_user_id_created_at_idx 
  on public.notification_logs (user_id, created_at desc);
alter table public.notification_logs enable row level security;
drop policy if exists "Users can read own notification logs"
  on public.notification_logs;
create policy "Users can read own notification logs"
  on public.notification_logs
  for select
  to authenticated
  using (user_id = auth.uid());
