create table if not exists public.link_outbound_events (
  id bigint generated by default as identity primary key,
  link_id uuid not null references public.links(id) on delete cascade,
  short_code text not null,
  stage text not null check (stage in ('primary', 'secondary')),
  destination_url text not null,
  source text,
  source_detail text,
  referer text,
  user_agent text,
  ip_address text,
  created_at timestamptz not null default now()
);

create index if not exists link_outbound_events_link_id_created_at_idx
  on public.link_outbound_events (link_id, created_at desc);

create index if not exists link_outbound_events_short_code_created_at_idx
  on public.link_outbound_events (short_code, created_at desc);

alter table public.link_outbound_events enable row level security;

drop policy if exists "Users can read outbound events of own links"
  on public.link_outbound_events;

create policy "Users can read outbound events of own links"
on public.link_outbound_events
for select
to authenticated
using (
  exists (
    select 1
    from public.links
    where links.id = link_outbound_events.link_id
      and links.user_id = auth.uid()
  )
);
